[plat]
# The base address of the user space.
user-space-base = 0x0000
# The base address for user interpreter.
user-interp-base = 0x400_0000
# The size of the user space.
user-space-size = 0x7_ffff_ffff

# The highest address of the user stack.
user-stack-top = 0x8000_0000
# The size of the user stack.
user-stack-size = 0x10_0000

# The lowest address of the user heap.
user-heap-base = 0x2000_0000
# The size of the user heap.
user-heap-size = 0x4000_0000

# The size of the kernel stack.
kernel-stack-size = 0x40000

# 信号栈基址（用户栈下方）
signal-stack-base = 0x3_fffe_0000
# 信号栈大小（4KB）
signal-stack-size = 0x1000
# trampoline基址
user-trampoline-base = 0x5_0000_0000

# Size of the whole physical memory. (1G)
#phys-memory-size = 0x4000_0000      # uint

