[package]
name = "axsyscall"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
syscalls = "0.6.18"
arceos_posix_api = { workspace = true , features = ["fd","fs","net"] }
