# Architecture identifier.
arch = "riscv64" # str
# Platform identifier.
platform = "riscv64-visionfive2" # str

#
# Platform configs
#
[plat]
# Platform family.
family = "riscv64-visionfive2" # str

# Base address of the whole physical memory.
phys-memory-base = 0x8000_0000 # uint
# Size of the whole physical memory. (128M)
#phys-memory-size = 0x800_0000       # uint
# Size of the whole physical memory. (1G)
phys-memory-size = 0x4000_0000 # uint
# Base physical address of the kernel image.
kernel-base-paddr = 0x8020_0000 # uint
# Base virtual address of the kernel image.
#kernel-base-vaddr = "0xffff_ffc0_8020_0000"     # uint
kernel-base-vaddr = "0xffff_ffc0_8020_0000" # uint
# Linear mapping offset, for quick conversions between physical and virtual
# addresses.
phys-virt-offset = "0xffff_ffc0_0000_0000" # uint
# Offset of bus address and phys address. some boards, the bus address is
# different from the physical address.
phys-bus-offset = 0 # uint
# Kernel address space base.
kernel-aspace-base = "0xffff_ffc0_0000_0000" # uint
# Kernel address space size.
kernel-aspace-size = "0x0000_003f_ffff_f000" # uint

#
# Device specifications
#

[devices]
mmio-regions = [
  [0x1000_0000, 0x1000],       # UART0 (console)
  [0x1001_0000, 0x1000],       # UART1 (console)
  [0x0c00_0000, 0x400_0000],   # PLIC
  [0x9_4000_0000, 0x100_0000], #PCI
] # [(uint, uint)]

# TODO: JH7110 有两个pci设备
pci-ecam-base = 0x940000000 # uint

# End PCI bus number (`bus-range` property in device tree).
pci-bus-end = 0xff # uint
pci-ranges = [
  [0x0, 0x0],                  # unused
  [0x9_4000_0000, 0x100_0000],
  [0x9_4000_0000, 0x100_0000],
] # [(uint, uint)]

timer-frequency = 1000_0000 # uint

# RTC (Real-Time Clock) Address
# 您 U-Boot DTS 中没有明确的 RTC 地址，QEMU 的 Goldfish RTC 在 JH7110 上不存在。
# 如果 JH7110 有 RTC，需要查找其地址。通常集成在 PMIC 或其他 IP 中。
# 暂时移除或注释掉，直到您确定 JH7110 的 RTC 地址。
#rtc-paddr = 0x10_1000               # uint
