[package]
name = "testcase"
version = "0.1.0"
edition = "2024"

[workspace]
[features]
[dependencies]
axstd = { path = "../../ulib/axstd"}
axfs = { path = "../../modules/axfs"}
axalloc = { path = "../../modules/axalloc"}
[build-dependencies]
acbat = { path = "../../modules/acbat"}
