[workspace]
resolver = "2"

members = [
  "modules/*",
  #"crates/*",

  "api/axfeat",
  "api/arceos_api",
  "api/arceos_posix_api",

  "ulib/axstd",
  "ulib/axlibc",

  "examples/helloworld",
  "examples/httpclient",
  "examples/httpserver",
  "examples/httpserver",
  "examples/shell",
  "examples/TCP_test",
  "ulib/axsyscall",
  "ulib/axmono", "ulib/axrand",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
#authors = ["Yuekai Jia <equation618@gmail.com>", "ZreXoc <zeexoc@outlook.com>", "LEOibyug <y2695719556@outlook.com>"]
authors = [
  "Yuekai Jia <equation618@gmail.com>",
  "ZreXoc <zeexoc@outlook.com>",
  "MukioXun <3045859462@qq.com>",
  "LEOibyug <y2695719556@outlook.com>",
]
license = "GPL-3.0-or-later OR Apache-2.0 OR MulanPSL-2.0"
homepage = "https://github.com/AstranciA/AstrancE"
documentation = "https://github.com/AstranciA/AstrancE"
repository = "https://github.com/AstranciA/AstrancE"
keywords = ["arceos", "kernel"]
categories = ["os", "no-std"]

[workspace.dependencies]
axstd = { path = "ulib/axstd" }
axlibc = { path = "ulib/axlibc" }
axmono = { path = "ulib/axmono" }
arceos_api = { path = "api/arceos_api" }
arceos_posix_api = { path = "api/arceos_posix_api" }
axfeat = { path = "api/axfeat" }

axalloc = { path = "modules/axalloc", features = ["page-alloc-4g"] }
axconfig = { path = "modules/axconfig" }
axdisplay = { path = "modules/axdisplay" }
axdriver = { path = "modules/axdriver" }
axfs = { path = "modules/axfs", features = ["lwext4_rs"] }
axhal = { path = "modules/axhal", features = ["uspace"] }
axlog = { path = "modules/axlog" }
axsignal = { path = "modules/axsignal" }
axmm = { path = "modules/axmm", features = ["mmap", "heap", "COW"] }
axnet = { path = "modules/axnet" }
axns = { path = "modules/axns", features = ["thread-local"] }
#axns = { git = "https://github.com/oscomp/arceos.git", features = [
#"thread-local",
#] }
axruntime = { path = "modules/axruntime" }
axsync = { path = "modules/axsync" }
axtask = { path = "modules/axtask" }
axdma = { path = "modules/axdma" }
axsyscall = { path = "ulib/axsyscall" }
acbat = { path = "modules/acbat" }
axptr = { path = "modules/axptr" }
syscalls = { git = "https://github.com/jasonwhite/syscalls.git", default-features = false, features = [
  "loongarch64",
  "riscv64",
] }
axfdt = { path = "./crates/axfdt" }

memory_set = { path = "./crates/axmm_crates/memory_set", features = ["RAII"] }
memory_addr = { path = "./crates/axmm_crates/memory_addr" }
page_table_multiarch = { path = "./crates/page_table_multiarch/page_table_multiarch" }
page_table_entry = { path = "./crates/page_table_multiarch/page_table_entry" }
axfs_vfs = { path = "./crates/axfs_crates/axfs_vfs" }
axfs_devfs = { path = "./crates/axfs_crates/axfs_devfs" }
axfs_ramfs = { path = "./crates/axfs_crates/axfs_ramfs" }
axfs_procfs = { path = "./crates/axfs_crates/axfs_procfs" }
axdriver_base = { path = "./crates/axdriver_crates/axdriver_base" }
axdriver_block = { path = "./crates/axdriver_crates/axdriver_block" }
axdriver_net = { path = "./crates/axdriver_crates/axdriver_net" }
axdriver_pci = { path = "./crates/axdriver_crates/axdriver_pci" }
axdriver_virtio = { path = "./crates/axdriver_crates/axdriver_virtio" }
lwext4_rust = { path = "./crates/lwext4_rust", default-features = false }
bitflags = "2.9.0"
linkme = "0.3.32"
weak-map = { git = "https://github.com/Starry-OS/weak-map.git" }
linux-raw-sys = { version = "0.9.4", default-features = false, features = [
  "no_std",
  "general",
  "net",
  "prctl",
  "system",
] }

#[patch.crates-io]
#page_table_multiarch = { git = "https://github.com/oscomp/page_table_multiarch.git", rev = "c8a13b0"}
#page_table_entry = { git = "https://github.com/oscomp/page_table_multiarch.git", rev = "c8a13b0" }

[profile.release]
lto = true

#[patch.crates-io]
#page_table_multiarch = { git = "https://github.com/Mivik/page_table_multiarch.git", rev = "19ededd" }
#page_table_entry = { git = "https://github.com/Mivik/page_table_multiarch.git", rev = "19ededd" }

[patch.crates-io]
memory_addr = { version = "0.3.2", path = "./crates/axmm_crates/memory_addr" }
page_table_multiarch = { path = "./crates/page_table_multiarch/page_table_multiarch" }
page_table_entry = { path = "./crates/page_table_multiarch/page_table_entry" }
axfs_vfs = { path = "./crates/axfs_crates/axfs_vfs" }
axfs_devfs = { path = "./crates/axfs_crates/axfs_devfs" }
axfs_ramfs = { path = "./crates/axfs_crates/axfs_ramfs" }
lwext4_rust = { path = "./crates/lwext4_rust" }
cty = { git = "https://github.com/MukioXun/cty.git" }

[patch.'https://github.com/Azure-stars/lwext4_rust.git']
lwext4_rust = { path = "./crates/lwext4_rust" }


[patch."https://github.com/arceos-org/axdriver_crates.git"]
axdriver_base = { path = "./crates/axdriver_crates/axdriver_base" }
axdriver_block = { path = "./crates/axdriver_crates/axdriver_block" }
axdriver_net = { path = "./crates/axdriver_crates/axdriver_net" }
axdriver_pci = { path = "./crates/axdriver_crates/axdriver_pci" }
axdriver_virtio = { path = "./crates/axdriver_crates/axdriver_virtio" }
