# Architecture identifier.
arch = "loongarch64"
logo = "AstrancE.png"
nodename = "AstrancR"
# Platform identifier.
platform = "loongarch64-qemu-virt"
release = "0.1"
# Number of CPUs
smp = 1 # uint
sysname = "AstrancE"
# Stack size of each task.
task-stack-size = 0x40000 # uint
# Number of timer ticks per second (Hz). A timer tick may contain several timer
# interrupts.
ticks-per-sec = 100 # uint
version = "0.1"

#
# Device specifications
#
[devices]
# poweroff {
#     value = <0x00000034>;
#     offset = <0x00000000>;
#     compatible = "syscon-poweroff";
# };
# ged@100e001c {
#     reg-io-width = <0x00000001>;
#     reg-shift = <0x00000000>;
#     reg = <0x00000000 0x100e001c 0x00000000 0x00000003>;
#     compatible = "syscon";
# };
ged-paddr = 0x100E001C # uint
# MMIO regions with format (`base_paddr`, `size`).
mmio-regions = [
    [0x100E_0000, 0x0000_1000],
    [0x1FE0_0000, 0x0000_1000],
    [0x2000_0000, 0x1000_0000],
    [0x4000_0000, 0x0002_0000]
] # [(uint, uint)]
# End PCI bus number.
pci-bus-end = 0x7f # uint
# Base physical address of the PCIe ECAM space.
pci-ecam-base = 0x2000_0000 # uint
# PCI device memory ranges.
pci-ranges = [
    [0, 0],
    [0x4000_0000, 0x0002_0000]
] # [(uint, uint)]
# Timer interrupt frequency in Hz.
timer-frequency = 100_000_000 # uint
# serial@1fe001e0 {
#     interrupt-parent = <0x00008003>;
#     interrupts = <0x00000002 0x00000004>;
#     clock-frequency = <0x05f5e100>;
#     reg = <0x00000000 0x1fe001e0 0x00000000 0x00000100>;
#     compatible = "ns16550a";
# };
uart-paddr = 0x1FE001E0 # uint
# VirtIO MMIO regions with format (`base_paddr`, `size`).
virtio-mmio-regions = [] # [(uint, uint)]

#
# Platform configs
#
[plat]
# Platform family.
family = "loongarch64-qemu-virt"
# Kernel address space base.
kernel-aspace-base = "0xffff_0000_0000_0000" # uint
# Kernel address space size.
kernel-aspace-size = "0x0000_ffff_ffff_f000" # uint
# Base physical address of the kernel image.
kernel-base-paddr = 0x8000_0000 # uint
# Base virtual address of the kernel image.
kernel-base-vaddr = "0xffff_0000_8000_0000" # uint
# The size of the kernel stack.
kernel-stack-size = 0x40000
# Offset of bus address and phys address. some boards, the bus address is
# different from the physical address.
phys-bus-offset = 0 # uint
# Base address of the whole physical memory.
phys-memory-base = 0x8000_0000 # uint
# Size of the whole physical memory. (128M)
phys-memory-size = 0x800_0000 # uint
# Linear mapping offset, for quick conversions between physical and virtual
# addresses.
phys-virt-offset = "0xffff_0000_0000_0000" # uint
# The lowest address of the user heap.
user-heap-base = 0x4000_0000
# The size of the user heap.
user-heap-size = 0x1_0000
# The base address for user interpreter.
user-interp-base = 0x400_0000
# The base address of the user space.
user-space-base = 0x0000
# The size of the user space.
user-space-size = 0x3f_ffff_f000
# The size of the user stack.
user-stack-size = 0x1_0000
# The highest address of the user stack.
user-stack-top = 0x4_0000_0000
